### ISSUE TITLE
Please provide the exe file

### ISSUE THREAD

**Issue by LisaJackson24-2** [RobertSmits/Windows-10-HotCorners#1]
Thank you for the app, although I haven't actually tried it because there are too many prerequisites for its use (having to compile the executable myself). It would be great if you could provide the pre-compiled executable file. This would be more user-friendly.

Also, I think that the program works not only on Windows 10, but also on Windows 11. Therefore, it would be worth changing the name a little.

I hope you will take my recommendations and suggestions into account. Wish you a good day.

Sincerely,
Lisa Jackson

**Comment by RobertSmits** [comment]
I have created a release and an executable is available

**Comment by LisaJackson24-2** [comment]
> I have created a release and an executable is available

Great, thanks for letting me know. But I found an annoying problem when the "DisableOnFullScreen" option is set to "true", then re-pointing to the corner does not close/repeat the action, i.e. it does not cycle. I'm using the top left corner for the TaskView, so hovering over the corner again doesn't close it.

And one more thing, without the nuance mentioned above, it works well on Windows 11, so I would still recommend changing the name to Hot Corners (as the configuration file is called), or to Windows Hot Corners, etc.

Also it wouldn't hurt to add some kind of app icon, I'll attach one as one of the possible options.

[Hot Corners.zip](https://github.com/RobertSmits/Windows-10-HotCorners/files/11994664/Hot.Corners.zip)

**Comment by LisaJackson24-2** [comment]
And I also remembered, it would be great to be able to set the hot zone for each corner (for example, in 1px, 2px, 3px, etc., this would mean that the hot corner will work in a square of 1x1px, 2x2px, 3x3px etc., I showed more clearly in the picture), as well as the delay for each of them. You can simply enter the default values in the configuration file, and if necessary, everyone would be able to change them. Something like this:

{
  "LeftTopAction": "2px", "400ms", "TaskView",
  "LeftBottomAction": "1px", "1ms", "NoAction",
  "RightTopAction": "1px", "1ms" "NoAction",
  "RightBottomAction": "1px", "1ms" "NoAction",
  "MultiMonitor": false,
  "DisableOnFullScreen": false,
  "LogLevel": "None"
}

![1](https://github.com/RobertSmits/Windows-10-HotCorners/assets/125877645/7bbfec8b-e99c-4490-b3fa-63ba058906c5)
